[#54] Adding extra path and added a new error for the case where multiple assets are found
chshersh/tool-sync pull request #102
Opened 2022-09-19 14:38 UTC by MitchellBerend

Resolves #54 

This pr add an extra path that gets checked once the binary is downloaded from github. Additionally it also adds an error case where multiple matches are found.

### Additional tasks

- [ ] Documentation for changes provided/changed
- [ ] Tests added

2022-09-19 16:25 UTC, MitchellBerend commented
The config I tested with and its result.
```bash
$ cat tools.toml
# This config file was generated for version 0.1.0
#
# # tool-sync default configuration file
# https://github.com/chshersh/tool-sync
# This file was automatically generated by tool-sync
#####################################################
#
#
store_directory = "$HOME/rust/tool-sync/bin"
#
# tool-sync provides native support for some of the tools without the need to configure them
# Uncomment the tools you want to have them
#
# [bat]
# [difftastic]
# [exa]
# [fd]
[ripgrep]
# [tool-sync]
#
# To add configuration for other tools these are the config options:
[github]
        owner     = "cli" 
        repo      = "cli" 
        exe_name  = "gh"

        # Uncomment to download a specific version or tag.
        # Without this tag latest will be used
        tag       = "v2.14.7"

# Asset name to download on linux OSes
        asset_name.linux = "linux_amd64"
#
# uncomment if you want to install on macOS as well
# asset_name.macos = "apple-darwin"
#
# uncomment if you want to install on Windows as well
# asset_name.windows = "x86_64-pc-windows-msvc"
```


```bash
$ cargo run -- --config tools.toml sync 
   Compiling tool-sync v0.1.0 (/home/mitchell/rust/tool-sync)
    Finished dev [unoptimized + debuginfo] target(s) in 2.40s
     Running `target/debug/tool --config tools.toml sync`
❌  github 
Multiple name matches found for this asset:

	 * gh_2.14.7_linux_amd64.deb
	 * gh_2.14.7_linux_amd64.rpm
	 * gh_2.14.7_linux_amd64.tar.gz

Please add one of these to the config.
🔄  All done!                                                                                                                                                             📦  Estimated total download size: 2.01 MiB
✅  ripgrep 13.0.0   Completed!                                                                                                                                           ✨  Successfully installed 1 tools!
📁  Installation directory: /home/mitchell/rust/tool-sync/bin
```

2022-09-19 19:20 UTC, chshersh requested changes
This is a helpful message improvement 👍🏻 

As always, a few comments 🙂

2022-09-19 19:20 UTC, chshersh commented on src/model/tool.rs
> +                    .map(|asset| asset.to_owned())
I wonder, could we use `into_iter()` instead of `iter()` to avoid cloning values and return owned values from the list?

2022-09-19 19:20 UTC, chshersh commented on src/model/tool.rs
> +                            asset.iter().map(|item| item.name.clone()).collect();
Same comment about `into_iter()` here as well

2022-09-19 19:20 UTC, chshersh commented on src/model/tool.rs
> +                name: asset_name.to_string(),
Can we change asset names in this test to have unique test names in each element?
Just to test that the function actually returns different assets from every item and not just replicates the same asset name several times. An easy way to increase test coverage without adding new tests, just changing existing ones 🙂 
```suggestion
                name: "asset_1".to_string(),
```

2022-09-19 19:20 UTC, chshersh commented on src/sync/prefetch.rs
> +                            None
Indeed, this could be an expected error 🤔 
Nice catch!

2022-09-19 19:20 UTC, chshersh commented on src/sync/progress.rs
> +            .unwrap_or(MIN_TAG_SIZE);
Good catch! Indeed, we shouldn't use `unwrap()` at all and I'd love to ban all usages of `unwrap` (ideally with `clippy`). `expect` is always strictly better because it provides a more informative message.

2022-09-20 06:23 UTC, MitchellBerend commented on src/model/tool.rs
> +                    .map(|asset| asset.to_owned())
This does not work here unfortunately since `assets` is used again on line 90.

2022-09-20 06:29 UTC, MitchellBerend commented on src/sync/prefetch.rs
> +                    prefetch_progress.unexpected_err_msg(tool_name, &e);
Actually this signature can take ownership. A reference can still be passed in and the compiler just knows its not moved even though the signature says it takes ownership.

2022-09-20 07:46 UTC, MitchellBerend commented
@chshersh The hardcoded `gh` binary on mac now downloads the amd64 version, it does not support arm (yes) but this might be possible in the future. The same is true for x86 and arm for linux, should there be an error in the realm of: 

hey your arch is x but this config/hardcoded tool currently downloads y, add <the correct config block> to your .tool.toml

2022-09-20 09:52 UTC, chshersh reviewed
One more question in the review.

About `arm64` — agree, let's keep it for future improvements. Currently, `tool-sync` matches only on [`env::consts::OS`](https://doc.rust-lang.org/std/env/consts/constant.OS.html) but when we want to support an arch, we need to handle [`env::consts::ARCH`](https://doc.rust-lang.org/std/env/consts/constant.ARCH.html) as well. This will complicate the logic significantly (especially when we want to support automatic asset name guess) so this would require a proper thinking ahead 🙂

2022-09-20 09:52 UTC, chshersh commented on .github/workflows/ci.yml
> +          if [[ ! -x $SYNC_DIR/gh  ]]; then echo "error on: gh";  false; fi
Once #93 is done, we won't need to change add new checks for new tools anymore 🤞🏻

2022-09-20 09:52 UTC, chshersh commented on src/model/tool.rs
> +                    .map(|asset| asset.to_owned())
Isn't this an error?

On line 90, you extract `name` from all original assets fetched from GitHub. I think, it would be better to show only those assets that match the provided query.

So, I imagine, if you add an asset with non-matching name in the `multiple_asset_found` test, the test would expect this non-matching asset as well. And I think we want to show only matching assets.

Or do I read the code incorrectly? 🤔

2022-09-20 10:30 UTC, MitchellBerend commented
> On line 90, you extract name from all original assets fetched from GitHub. I think, it would be better to show only those assets that match the provided query.

The variable naming is not optimal here.

This part has `asset` contain a `Vec<Asset>` with only matches.
https://github.com/chshersh/tool-sync/blob/265e1f3105291e979c4ccc6704515ea3d66151f8/src/model/tool.rs#L79-L83

This part then pulls out the names of all matches.
https://github.com/chshersh/tool-sync/blob/265e1f3105291e979c4ccc6704515ea3d66151f8/src/model/tool.rs#L90-L91

This should probably be ensured in the test though so I will add an asset that does not match.

2022-09-20 11:59 UTC, chshersh approved these changes
Looks terrific 🏆

2022-09-20 12:00 UTC, merged