[#92] Install a tool from the config file using `tool sync <tool-name>`
chshersh/tool-sync pull request #113
Opened 2022-09-21 01:15 UTC by zixuanzhang-x

Resolves #92 

Added an optional <TOOL> argument for the `sync` command to install a single tool from the config file. If no <TOOL> argument is specified, `sync` will install all the tools from the config file.

### Additional tasks

- [x] Documentation for changes provided/changed
- [ ] Tests added

2022-09-21 11:12 UTC, chshersh requested changes
Looks like a great change! 👏🏻 

@zixuanzhang-x Could you try to run `tool sync xyz` with a tool in the config and not in the config and share some screenshots to show how it works?

It would be great to add tests but it might be a bit of work with the current test setup. It should be easier to add tests once #93 is done 🙂 

Also, could you add your changes to the `Unreleased` section in CHANGELOG and update the [Usage section](https://github.com/chshersh/tool-sync#usage) in README with an example of syncing a single tool? 🙏🏻

2022-09-21 11:12 UTC, chshersh commented on src/sync.rs
> +}
This has some code duplication with the `install` command:

https://github.com/chshersh/tool-sync/blob/df7d4768c9cff2a91616bd9686bc928a52fc8c10/src/install.rs#L17-L20

Could you instead create a function called `sync_single_tool` that will take as arguments a mutable config, a tool name, `ConfigAsset`, and then creates a singleton map from that and runs `sync_from_config_no_check`?

You can then use this function in both places

2022-09-21 11:12 UTC, chshersh commented on src/sync.rs
> +                sync_tool_no_check(config, tool);
You can use [`get`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.get) here and match on the resulting `Option` instead of checking if the value is in the map. This way you'll perform only one lookup in the map instead of two. And you also won't need to do `(*config.tools.get(&tool).unwrap())`

2022-09-21 11:12 UTC, chshersh commented on src/sync.rs
> +    );
Let's improve the message even further 🙂 

```suggestion
        r#"The '{}' tool is not listed in the configuration file: {}.

Add the tool to the configuration file or use the 'tool install' command for installing one of the tools natively supported by 'tool-sync'."#,
        tool,
        path,
    );
```

2022-09-22 02:48 UTC, zixuanzhang-x commented on src/sync.rs
> +}
good idea

2022-09-22 02:49 UTC, zixuanzhang-x commented on src/sync.rs
> +                sync_tool_no_check(config, tool);
got it, it does make the code simpler

2022-09-22 03:09 UTC, zixuanzhang-x commented
Here're the screenshots of running `tool sync <tool-name>` when the tool is and is not in the config:
<img width="822" alt="Screen Shot 2022-09-21 at 10 59 15 PM" src="https://user-images.githubusercontent.com/74850854/191649718-4780b2a6-6586-481e-8cfd-73dd08e69077.png">
<img width="966" alt="Screen Shot 2022-09-21 at 11 06 18 PM" src="https://user-images.githubusercontent.com/74850854/191649684-65f68998-b09a-4139-8015-37bacc99ab7b.png">

2022-09-23 00:19 UTC, zixuanzhang-x commented on src/sync.rs
> +            Some(asset) => sync_single_tool(config.clone(), tool, (*asset).clone()),
oh nice, with the `remove` method I don't need `clone()` indeed.

The reason I previously cloned config is that rust complains `cannot move borrowed value` because config is borrowed in the `match` clause.

2022-09-23 00:27 UTC, chshersh approved these changes
Amazing job! 🚀

2022-09-23 00:27 UTC, merged