[#84] refactor of hardcoded tools
chshersh/tool-sync pull request #114
Opened 2022-09-21 13:41 UTC by MitchellBerend

Resolves #84 

This pr aims to simplify the way tools are added so that there aren't any `into()` calls to convert from `&str` to `String`.

### Additional tasks

- [ ] Documentation for changes provided/changed
- [ ] Tests added

2022-09-21 13:47 UTC, MitchellBerend commented on src/sync/db.rs
>  }
@chshersh can you take a look at this `fmt_tool_names` function? It takes a closure and I tried changing the argument to `&str` but the compiler is giving some type errors and I can't figure out how to resolve them.

2022-09-21 13:58 UTC, MitchellBerend commented on src/sync/db.rs
>  }
Nvm I think wrapping the `std::collections::BTreeMap` in an internal one with another `From` implementation to convert between the 2 works fine.

2022-09-21 23:21 UTC, chshersh requested changes
This looks super neat! 💎 

I have a few ideas about simplifying the code but I like how much nicer it looks now 🤤

2022-09-21 23:21 UTC, chshersh commented on src/sync/db.rs
> +            windows: "x86_64-pc-windows-msvc",
This looks so much cleaner and nicer 🤌 

Maybe, one day we'll move all the tools to a TOML file. But I'm not sure about the best way to distribute it and I don't want to download it on start and store somewhere. So... This should be fine for now 🆗

2022-09-21 23:21 UTC, chshersh commented on src/sync/db.rs
> +        Self {
Can we use the `ToolInfo` constructor here for more explicitness?
```suggestion
        ToolInfo {
```

2022-09-21 23:21 UTC, chshersh commented on src/sync/db.rs
> +                windows: from_supported_asset(static_tool_info.windows.to_string()),
Can we make `from_supported_asset` accept `&'static str` and remove `to_string()` from here?

It'll stil probably remain in `Some(asset_name.to_string())`. But I think the conversion function will be cleaner. And it could potentially safe some performance when the value is `NOT_SUPPORTED` and we can avoid redundant conversion

2022-09-21 23:21 UTC, chshersh commented on src/sync/db.rs
> +}
A separate wrapper data type for `BTreeMap` feels a bit clunky. Let's use a different (more functional) approach.

In line 15, we can create:

```rust
let mut tools: BTreeMap<&'static str, StaticToolInfo> = BTreeMap::new();
```

And then, we can return:

```rust
BTreeMap::from_iter(
    tools
        .into_iter()
        .map(|(k, v)| (k.to_owned(), v.into()))
)
```

We'll just convert one `BTreeMap` to another by mapping both key and value.

<hr>

I tried playing a bit with `&'static str` but also had some weird errors with `FnMut`. So, let's try a simpler approach. I'm still not fluent with Higher-Order Functions in the Rust sense 🥴

2022-09-22 06:09 UTC, MitchellBerend commented on src/sync/db.rs
> +        Self {
I will change the return type as well. I always return `Self` so if the name of the struct changes it's that many less places that also need  change.

2022-09-22 06:17 UTC, MitchellBerend commented on src/sync/db.rs
> +}
This is actually a way simpler approach. I tried looking for a solution in the `fmt_tool_names` function as well but it got messy quite quickly.

2022-09-22 06:19 UTC, MitchellBerend commented on src/sync/db.rs
> +                windows: from_supported_asset(static_tool_info.windows.to_string()),
Ah yes there might be some `""` that get converted to `String` for no reason. I initially had them here so the `From` trait would do all the conversion, but this is a good reason to move the conversion.

2022-09-22 06:23 UTC, MitchellBerend commented on src/sync/db.rs
> +        .into(),
This `into()` call is now moved to the `map` at the end of the function. Imo the way tools are added now is very clean.

2022-09-22 12:33 UTC, merged