Provide more detailed TOML decoding errors
chshersh/tool-sync pull request #122
Opened 2022-10-01 04:24 UTC by DukeManh

Fixes #25 

Provide more detailed TOML decoding errors by adding `DecodeError` enum to represent different error types.

Author's questions:

> Does the toml crate provide better decoding than as_str() and friends? All such functions return Option<...> while it would be better to have Result<..., ...>

I couldn't find better decoding than as_str() but I did map `Option<>` to `Result<_, DecodeError>` so I guess dealing with Option is fine?

### Additional tasks

- [ ] Documentation for changes provided/changed
- [ ] Tests added
- [ ] Updated CHANGELOG.md

2022-10-01 04:29 UTC, DukeManh commented on src/config/toml.rs
> +    NotATable,
I'm not sure how to trigger this error case yet though it can happen on line 85. I find out that the config file is always a table if we have `store_directory` defined, which is checked before line 85.

2022-10-01 17:31 UTC, chshersh requested changes
Hey @DukeManh,

That's a great start! I propose to go one step further and implement the following design:

- [ ] Introduce a separate data type for `TOML` value types:

```rust
enum TomlType {
    String,
    Integer,
    Float,
    Boolean,
    Datetime,
    Array,
    Table,
}
```

- [ ] Implement `DecodeError` as the following enum, listing all possible errors (very similar to yours but with a few changes):

```rust
pub enum DecodeError {
    /// Missing required TOML key
    MissingKey { key: String },

    /// Expecting a different type of an existing key
    InvalidType { key: String, expected: TomlType, found: toml::Value },
}
```

- [ ] Then, create a `Result<_, DecodeError>` versions of all standard functions from `toml` (but not like all-all, it's not enough only for those that we use. I believe, it's only `as_str` and `as_table`). So it should look something like this:

```rust
fn parse_str(toml: &toml::Value, key: &str) -> Result<String, DecodeError> { ... }
```

In that case, I believe we should be able to use the `?` operator and return the first found error.

Ideally, we want to return all possible errors at once. But that would be more complicated so let's start with this 😌

2022-10-01 19:29 UTC, DukeManh commented
@chshersh That's a great suggestion, I'm on it.

2022-10-01 20:10 UTC, DukeManh commented
I have some questions.

> Introduce a separate data type for TOML value types

Why do we need a separate type for toml and not use `toml::value`?
>  we want to return all possible errors at once.

Is it something you have in mind? https://doc.rust-lang.org/rust-by-example/error/multiple_error_types.html

2022-10-03 11:51 UTC, chshersh commented
> Why do we need a separate type for toml and not use toml::value?

`toml::Value` also stores data inside. When we decode TOML, we don't expect any specific data, we expect only the shape of Data. So, unfortunately, we can't reuse `toml::Value` here.

> Is it something you have in mind? https://doc.rust-lang.org/rust-by-example/error/multiple_error_types.html

No, more like something similar:

* https://www.fpcomplete.com/blog/collect-rust-traverse-haskell-scala/#validation

2022-10-05 19:47 UTC, DukeManh commented
@chshersh this is ready, can you review it, please?

2022-10-06 23:38 UTC, chshersh requested changes
This looks excellent! 👏🏻 
I expected waaaay more changes to support this but it turned out to be quite small 🙂 

I have a few stylistic suggestions and some questions. But overall, the direction is correct 👍🏻

2022-10-06 23:38 UTC, chshersh commented on src/config/toml.rs
> +#[allow(dead_code)]
Just curious why this line is needed? 🤔

2022-10-06 23:38 UTC, chshersh commented on src/config/toml.rs
> +        .and_then(|toml| decode_config(toml).map_err(TomlError::Decode))
That's a neat simplification enabled by the improvement! 💯

2022-10-06 23:38 UTC, chshersh commented on src/config/toml.rs
> +                found.type_str()
Wow, `type_str` is a neat function! I didn't know it exists and it's actually the idea behind the `TomlType` enum.

2022-10-06 23:38 UTC, chshersh commented on src/config/toml.rs
> +            TomlType::Table => "table",
Would be nice to reuse `type_str` here and avoid duplication but I don't see a non-ugly way to do this 🤔

2022-10-06 23:38 UTC, chshersh commented on src/config/toml.rs
> +    let table = toml.as_table().unwrap();
Could we use `expect` with a unique message string here instead of `unwrap`?

2022-10-06 23:38 UTC, chshersh commented on src/config/toml.rs
> +                write!(f, "'{}' is not configured", key)
Let's change a wording a bit here
```suggestion
                write!(f, "The key '{}' is missing (a typo or not specified?)", key)
```

2022-10-08 18:37 UTC, DukeManh commented on src/config/toml.rs
> +#[allow(dead_code)]
The compiler warns that I'm only using `TomlType::String` on line 129 so other types are unused. I am just doing this to suppress that. Maybe comment out the used types for now?

2022-10-08 18:38 UTC, DukeManh commented on src/config/toml.rs
> +    let table = toml.as_table().unwrap();
nice, I didn't know it existed

2022-10-08 19:09 UTC, DukeManh commented
@chshersh, I decided to reuse `toml::Value` and `type_str` to represent our expected type. What do you think?

2022-10-09 11:40 UTC, chshersh approved these changes
I like this implementation! Indeed, it's much simpler 🙂 
Thanks a lot for improving error messages! 👏🏻

2022-10-09 11:41 UTC, merged