[#133] Added concept completion implementation
chshersh/tool-sync pull request #134
Opened 2022-10-10 11:25 UTC by MitchellBerend

Resolves #133 

This pr aims to add a tab completion script so users don't have to remember every command if they want to experiment with config options.

### Additional tasks

- [ ] Documentation for changes provided/changed
- [ ] Tests added
- [ ] Updated CHANGELOG.md

2022-10-10 11:28 UTC, MitchellBerend commented on src/lib.rs
> +}
@chshersh I might be going crazy here, does line 37 not ensure the type of `cmd` is `clap::Command`?

2022-10-10 11:46 UTC, MitchellBerend commented on src/lib.rs
> +}
Okay it turns out I didn't pick the correct `clap_complete` version :sweat:

2022-10-11 18:42 UTC, MitchellBerend commented
It does, the way it is implemented in the pr right now it gets the name automatically. There is an easy way to override this with `tool` (or anything for that matter)

2022-10-13 13:00 UTC, MitchellBerend commented
Yes I would, I put a blocked tag on the issue itself. I don't think i can put labels on prs but consider this one blocked until #136 is resolved.

2022-10-13 20:45 UTC, SanchithHegde commented
@MitchellBerend Sorry to have kept you waiting, I've opened #137 for the `clap-4.0` upgrade.

2022-10-14 03:49 UTC, MitchellBerend commented
@SanchithHegde don't worry about it, Im at a convention anyway 😅.

2022-10-14 07:43 UTC, MitchellBerend commented
@chshersh In my opinion we should have a consistent naming convention throughout the entire code base. I think #130  would also benefit from that since there would be a clear way to prefix environment variables.

2022-10-14 16:09 UTC, MitchellBerend commented
There is an issue with the help text of the current `completion` command. Because some lines are indented they get interpreted as rust code and as such they will be ran through the docs tests. Since those indented lines are (mostly) bash scripts they don't pass docs tests in ci. 

There is a config option (`#[cfg(not(doctest))]`) that disables the doc test for an entire module and since this issue is contained in the `src/config/cli.rs` file this would work, but I get weird compiler errors trying to add this.

Im not sure if I like the way the formatting looks when the indentation are removed. I added ` around the commands to make it a little clearer but this still looks kind of like a wall of text to me.

There is an [issue](https://github.com/rust-lang/rust/issues/63193) filed on the main rust repo for this already.

2022-10-14 16:10 UTC, MitchellBerend commented
Sample output: 
```
mitchell@mitchell-workstation:~/rust/tool-sync$ cargo run -- completion --help 
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/tool completion --help`
Generate shell completion scripts for GitHub CLI commands.

You will need to set up completions manually, follow the instructions below. The exact config file locations might vary based on your system. Make sure to restart your shell before testing whether completions are working.

### bash

First, ensure that you install `bash-completion` using your package manager.

After, add this to your `~/.bash_profile`:

`eval "$(tool completion bash)"`

### zsh

Generate a `_tool` completion script and put it somewhere in your `$fpath`:

`tool completion zsh > /usr/local/share/zsh/site-functions/_tool`

Ensure that the following is present in your `~/.zshrc`:

`autoload -U compinit` `compinit -i`

Zsh version 5.7 or later is recommended.

### fish

Generate a `tool.fish` completion script:

`tool completion fish > ~/.config/fish/completions/tool.fish`

### PowerShell

Open your profile script with:

`mkdir -Path (Split-Path -Parent $profile) -ErrorAction SilentlyContinue` `notepad $profile`

Add the line and save the file:

`Invoke-Expression -Command $(tool completion powershell | Out-String)`

Usage: tool completion <SHELL>

Arguments:
  <SHELL>
          [possible values: bash, elvish, fish, powershell, zsh]

Options:
  -h, --help
          Print help information (use `-h` for a summary)
```

2022-10-15 12:52 UTC, chshersh commented
@MitchellBerend Thanks for writing such detailed progress updates! The issue with doctest is annoying indeed. The solution with backticks sounds like a good trade-off. And thanks a lot for write great help text! 💯

2022-10-15 14:56 UTC, MitchellBerend commented
Sample output of current implementation

```
mitchell@mitchell-workstation:~/rust/tool-sync$ cargo run -- completion bash --rename asdfasdf -- $1 > /dev/null 
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/tool completion bash --rename asdfasdf --`
First, ensure that you install `bash-completion` using your package manager.

After, add this to your `~/.bash_profile`:

`eval "$(asdfasdf completion bash --rename asdfasdf)"`

----------------------------------------------------------------------------------------------------------------------------------------------------------------

mitchell@mitchell-workstation:~/rust/tool-sync$ cargo run -- completion fish --rename asdfasdf -- $1 > /dev/null 
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/tool completion fish --rename asdfasdf --`
Generate a `tool.fish` completion script:

`asdfasdf completion fish --rename asdfasdf > ~/.config/fish/completions/asdfasdf.fish`

----------------------------------------------------------------------------------------------------------------------------------------------------------------

mitchell@mitchell-workstation:~/rust/tool-sync$ cargo run -- completion zsh --rename asdfasdf -- $1 > /dev/null 
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/tool completion zsh --rename asdfasdf --`
Generate a `_asdfasdf` completion script and put it somewhere in your `$fpath`:
`asdfasdf completion zsh --rename asdfasdf > /usr/local/share/zsh/site-functions/_asdfasdf`

Ensure that the following is present in your `~/.zshrc`:

`autoload -U compinit`

`compinit -i`

----------------------------------------------------------------------------------------------------------------------------------------------------------------

mitchell@mitchell-workstation:~/rust/tool-sync$ cargo run -- completion powershell --rename asdfasdf -- $1 > /dev/null 
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/tool completion powershell --rename asdfasdf --`
Open your profile script with:

`mkdir -Path (Split-Path -Parent $profile) -ErrorAction SilentlyContinue`
`notepad $profile`

Add the line and save the file:

`Invoke-Expression -Command $(asdfasdf completion powershell --rename asdfasdf | Out-String)`

----------------------------------------------------------------------------------------------------------------------------------------------------------------

mitchell@mitchell-workstation:~/rust/tool-sync$ cargo run -- completion elvish --rename asdfasdf -- $1 > /dev/null 
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/tool completion elvish --rename asdfasdf --`
This suggestion is missing, if you use this and know how to implement this please file an issue over at https://github.com/chshersh/tool-sync/issues
```

2022-10-19 11:21 UTC, chshersh requested changes
This looks super great! 🏆 

I have a few suggestions on refactoring, documenting and changing the module structure a bit. But the implementation is superb ✨

2022-10-19 11:21 UTC, chshersh commented on README.md
> +the autocompletion will keep working.
Thanks a lot for updating the documentation! 👏🏻 

I think here is a good place. Could we also add two examples in the README for configuring a Bash shell completion with default settings and with renamed binary? Just to give a quick way to see how it works 👍🏻

2022-10-19 11:21 UTC, chshersh commented on src/config/cli.rs
> +    /// `Invoke-Expression -Command $(tool completion powershell | Out-String)`
That's an amazing documentation! 👏🏻 

I'm okay with with not supporting some exotic shells like Elvish. It's not even feasible to test this 😓

2022-10-19 11:21 UTC, chshersh commented on src/config/cli.rs
> +        /// If you want to renam the binary this option should be filled with the name you choose
A typo
```suggestion
        /// If you want to rename the binary this option should be filled with the name you choose
```

2022-10-19 11:21 UTC, chshersh commented on src/config/template.rs
> +// This function can break when clap_complete adds support for a new shell type
Will it break though? I see that the `Shell` type has the `#[non_exhaustive]` pragma. And we also handle all other shells with `_`.

So, in other words, the compiler won't output any errors if `clap_complete` adds new shells. They'll simply remain unsupported as now. And people can open new issues to request support for new shells 🙂

2022-10-19 11:21 UTC, chshersh commented on src/config/template.rs
> +        Shell::Elvish => r##"This suggestion is missing, if you use this and know how to implement this please file an issue over at https://github.com/chshersh/tool-sync/issues"##.into(),
I like this! 😅

2022-10-19 11:21 UTC, chshersh commented on src/config/template.rs
> +        Shell::Zsh => format!(r##"Generate a `_{bin_name}` completion script and put it somewhere in your `$fpath`:
I guess we can simplify this big `match` expression by extracting formatting logic into separate functions:

```rust
let completion_str: String = match shell {
    Shell::Zsh => zsh_completion_help(bin_name),
    Shell::Bash => bash_completion_help(bin_name),
    ...
```

This will make the match simpler and we can change help text for each function independently

2022-10-19 11:21 UTC, chshersh commented on src/lib.rs
> +}
I would put this instance near the `RenameError` enum. It feels natural to me to keep the type and trait implementations close to each other.

Also, I'd move the shell completion logic from `src/config/template.rs` to another module.

It's a separate command and currently each command has it's own module. Some refactoring is required for the existing commands but I'd move `generate_completion` and completion logic from `template.rs` into a separate module `src/completion.rs`

2022-10-19 11:36 UTC, MitchellBerend commented on src/config/template.rs
> +// This function can break when clap_complete adds support for a new shell type
I added that comment to clarify why there is a separate function for a simple match statement. Maybe this should include an error message along the lines of: 
```
This shell type is not implemented yet, please go over to https://github.com/chshersh/tool-sync to file an issue about its implementation.
```

2022-10-19 11:40 UTC, MitchellBerend commented on src/lib.rs
> +}
> I would put this instance near the RenameError enum. It feels natural to me to keep the type and trait implementations close to each other.

I forgot to copy this over with the rest :sweat_smile:

2022-10-20 10:42 UTC, chshersh approved these changes
Looks amazing! LFG 🚀

2022-10-20 10:42 UTC, merged