added tag support in download progress
chshersh/tool-sync pull request #64
Opened 2022-09-03 20:44 UTC by MitchellBerend

Resolves #63

Added a `max_tag_size` on `SyncProgress` to prepare the output message for tags
that are longer than normal.

```bash
$ cargo run -- --config test-tools.toml sync
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/tool --config test-tools.toml sync`
⛔  bat     asdkjhkasdjfaksjdfhk;j [error] https://api.github.com/repos/sharkdp/bat/releases/tags/asdkjhkasdjfaksjdfhk;j: status code 404
✅  exa     v0.10.1                Completed!
✅  fd      v8.4.0                 Completed!
✅  ripgrep 13.0.0                 Completed!

$ cat test-tools.toml 
# This file was automatically generated by tool-sync
#
store_directory = "./bins"

    [bat]
        owner =     "sharkdp"
        repo =      "bat"
        exe_name =  "bat"
        tag =       "asdkjhkasdjfaksjdfhk;j"
    [exa]
        owner =     "ogham"
        repo =      "exa"
        exe_name =  "exa"
        tag =       "v0.10.1"
    [fd]
        owner =     "sharkdp"
        repo =      "fd"
        exe_name =  "fd"
        tag =       "v8.4.0"
    [ripgrep]
        owner =     "BurntSushi"
        repo =      "ripgrep"
        exe_name =  "rg"
        tag =       "13.0.0"
```

2022-09-05 10:46 UTC, chshersh requested changes
Great and simple improvement 👍🏻 

I have a few suggestions for improving the code but the overall it looks great 👏🏻

2022-09-05 10:46 UTC, chshersh commented on src/sync.rs
> +        let sync_progress = SyncProgress::new(tools, tags);
It's a clever solution 👍🏻 
Indeed, we can assume that the version is `latest` if it's not specified in the config. So we can iterate through all of them before actually doing the processing.

Probably, in some future, we can improve this even further by fetching the release info about each tool first and producing the **real** version instead of `latest`. But that's a separate feature request 🙂

2022-09-05 10:46 UTC, chshersh commented on src/sync/progress.rs
> +            })
I would simplify this match by using [std::cmp::max](https://doc.rust-lang.org/std/cmp/fn.max.html) function, so it could be just `max(tag.len(), 8)` instead of `match ...`.

Also, let's move 8 to a top-level `const` with the name like `MIN_TAG_LEN` and use it everywhere

2022-09-05 10:46 UTC, chshersh commented on src/sync/progress.rs
> +mod tests {
The tests are 👨🏻‍🍳 🤌

2022-09-05 12:34 UTC, MitchellBerend commented on src/sync/progress.rs
> +            })
Good call actually on the const actually, this way there are stray numbers left in the code if the minimum size changes for whatever reason.

As for the map I think its more clear to use the absolute name as `max` is also called on the map itself after the collection is prepared. Is that acceptable or do you have a different suggestion?

```rust
        let max_tag_size = tags
            .iter()
            .map(|tag| std::cmp::max(tag.len(), MIN_TAG_SIZE) )
            .max()
            .unwrap_or(8);
```

2022-09-05 12:40 UTC, chshersh commented on src/sync/progress.rs
> +            })
I'm okay with using `std::cmp::max`, that sounds reasonable to me 👍🏻 

Do you also want to change the `.unwrap_or(8);` to `.unwrap_or(MIN_TAG_SIZE);`? I usually don't like magic numbers and it's better to avoid them when possible. I sometimes might be lazy and use a constant but it's not sustainable so let's improve the code that we use 🏡

2022-09-07 11:46 UTC, chshersh approved these changes
Looks amazing 👏🏻

2022-09-07 11:46 UTC, merged